services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    networks:
      - app_network
    depends_on:
      mysql:
        condition: service_healthy

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app_network
    depends_on:
      php:
        condition: service_started

  mysql:
    image: mysql:8.4
    container_name: Database
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  app_network:
    driver: "bridge"

volumes:
  mysql_data:
