FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libonig-dev \
    libzip-dev \
    libpng-dev \
    && docker-php-ext-install \
    pdo pdo_mysql mbstring \
    zip \
    gd \
    bcmath

COPY --from=composer:2.9 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

COPY composer*.json ./

RUN composer install --no-interaction --no-scripts --no-autoloader

COPY . .

RUN composer dump-autoload --optimize

ENTRYPOINT [ "docker-entrypoint.sh" ]

EXPOSE 8000

CMD ["php", "artisan", "serve", "--host", "0.0.0.0"]

